#!/usr/bin/python

import sys

def factorize(n):
    if n % 2 == 0:
        return 2, n // 2
    elif n % 3 == 0:
        return 3, n // 3

    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return i, n // i
    return n, 1

def main():
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        return

    filename = sys.argv[1]
    with open(filename, 'r') as file:
        for line in file:
            n = int(line.strip())
            p, q = factorize(n)
            print(f"{n}={p}*{q}")

if __name__ == "__main__":
    main()
