#!/usr/bin/python
import sys


def factorize(n):
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return n // i, i
    return n, n


def main():
    filename = sys.argv[1]
    with open(filename, 'r') as file:
        for line in file:
            n = int(line.strip())
            p, q = factorize(n)
            print(f"{n}={p}*{q}")


if __name__ == "__main__":
    main()
