#!/usr/bin/python3
def factorize(n):
    if n % 2 == 0:
        return 2, n // 2
    elif n % 3 == 0:
        return 3, n // 3
    return 1, n


def main():
    import sys
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        return
    with open(sys.argv[1], 'r') as f:
        for line in f:
            n = int(line.strip())
            p, q = factorize(n)
            print(f"{n}={p}*{q}")


if __name__ == "__main__":
    main()
